// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": memos_admin Resource Client
//
// Command:
// $ goagen
// --design=github.com/akm/gae_go-datastore-goa-goon-viron-react-redux-example/server/design
// --out=$(GOPATH)/src/github.com/akm/gae_go-datastore-goa-goon-viron-react-redux-example/server
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateMemosAdminPath computes a request path to the create action of memos_admin.
func CreateMemosAdminPath() string {

	return fmt.Sprintf("/admin/memos")
}

// create
func (c *Client) CreateMemosAdmin(ctx context.Context, path string, payload *MemoPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateMemosAdminRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateMemosAdminRequest create the request corresponding to the create action endpoint of the memos_admin resource.
func (c *Client) NewCreateMemosAdminRequest(ctx context.Context, path string, payload *MemoPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// DeleteMemosAdminPath computes a request path to the delete action of memos_admin.
func DeleteMemosAdminPath(id string) string {
	param0 := id

	return fmt.Sprintf("/admin/memos/%s", param0)
}

// delete
func (c *Client) DeleteMemosAdmin(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteMemosAdminRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteMemosAdminRequest create the request corresponding to the delete action endpoint of the memos_admin resource.
func (c *Client) NewDeleteMemosAdminRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ListMemosAdminPath computes a request path to the list action of memos_admin.
func ListMemosAdminPath() string {

	return fmt.Sprintf("/admin/memos")
}

// list
func (c *Client) ListMemosAdmin(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListMemosAdminRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListMemosAdminRequest create the request corresponding to the list action endpoint of the memos_admin resource.
func (c *Client) NewListMemosAdminRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UpdateMemosAdminPath computes a request path to the update action of memos_admin.
func UpdateMemosAdminPath(id string) string {
	param0 := id

	return fmt.Sprintf("/admin/memos/%s", param0)
}

// update
func (c *Client) UpdateMemosAdmin(ctx context.Context, path string, payload *MemoPayload, contentType string) (*http.Response, error) {
	req, err := c.NewUpdateMemosAdminRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateMemosAdminRequest create the request corresponding to the update action endpoint of the memos_admin resource.
func (c *Client) NewUpdateMemosAdminRequest(ctx context.Context, path string, payload *MemoPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
