anchors:
- &string_required
  type: string
  required: true
- &time_required
  type: time.Time
  required: true

types:
  User:
    goon:
      # id_type: int64
      # id_type: string
      # id_type: UUID (type: string)
      id_name: Email
      id_type: string
    fields:
      CreatedAt: *time_required
      UpdatedAt: *time_required
  Memo:
    goon:
      id_type: int64
      # id_type: string
      # id_type: UUID (type: string)
    payload: MemoPayload
    media_type: Memo
    fields:
      Content: string
      Shared: bool
      CreatedAt: *time_required
      UpdatedAt: *time_required
