version: 1
runtime: go
api_version: go1.9

handlers:
- url: /swagger.json
  script: _go_app
- url: /viron_authtype
  script: _go_app
- url: /viron
  script: _go_app

- url: /
  script: _go_app
  login: required

- url: /memos
  script: _go_app
  login: required
- url: /memos/.*
  script: _go_app
  login: required

- url: /index.html
  static_files: ui/index.html
  upload: ui/index.html

- url: /bundle.js
  static_files: ui/bundle.js
  upload: ui/bundle.js

nobuild_files:
- vendor/

skip_files:
- vendor/
