version: 1
runtime: go
api_version: go1.9

handlers:
# Paths for development
- url: /swagger.json
  script: _go_app
- url: /swaggerui/
  script: _go_app
  login: required
- url: /swaggerui/*.*
  script: _go_app
  login: required

# source map path for development
- url: /(.*\.map)$
  static_files: ui/\1
  upload: ui/(.*\.map)$

# Paths for production
- url: /
  script: _go_app
  login: required
- url: /memos
  script: _go_app
  login: required
- url: /memos/.*
  script: _go_app
  login: required
- url: /index.html
  static_files: ui/index.html
  upload: ui/index.html
- url: /bundle.js
  static_files: ui/bundle.js
  upload: ui/bundle.js

nobuild_files:
- vendor/

skip_files:
- vendor/
